In [1]:
import pandas as pd

df = pd.read_csv('/home/hbliu/tcn_data.csv')

In [2]:
df

Unnamed: 0    datetime instrument         open        close  \
0                  0  2008-01-02   SZ000001   999.571594   986.070923   
1                  1  2008-01-02   SZ000002  1589.811401  1599.124512   
2                  2  2008-01-02   SZ000004    58.051300    61.230598   
3                  3  2008-01-02   SZ000005    70.015198    70.801903   
4                  4  2008-01-02   SZ000006   259.752106   264.509094   
...              ...         ...        ...          ...          ...   
11716592    11716592  2023-11-20   SZ000517    43.630901    43.307701   
11716593    11716593  2023-11-20   SZ000518    25.862301    26.114201   
11716594    11716594  2023-11-20   SZ000519   116.475197   120.491600   
11716595    11716595  2023-11-20   SZ000520    20.182699    20.182699   
11716596    11716596  2023-11-20   SZ000521    32.446400    32.857201   

                 high          low        volume  total_turnover         vwap  \
0         1005.802673   977.503174  7.723510e+05    7.634657e+08   988.495705   
1         1616.655151  1555.297852  1.713655e+06    2.719854e+09  1587.165497   
2           61.583900    57.168201  8.619572e+05    5.156850e+07    59.827217   
3           71.982002    68.835197  1.625922e+06    1.149908e+08    70.723434   
4          266.392090   255.787903  3.532509e+05    9.237655e+07   261.504063   
...               ...          ...           ...             ...          ...   
11716592    43.954102    43.146099  1.116749e+06    4.848927e+07    43.420008   
11716593    26.282101    25.778299  1.404979e+06    3.669995e+07    26.121350   
11716594   122.007202   115.338501  7.539261e+06    8.991488e+08   119.262197   
11716595    20.182699    19.984200  2.596807e+06    5.219265e+07    20.098779   
11716596    33.113800    32.241100  5.871951e+06    1.921593e+08    32.724940   

          return_rate  
0                 NaN  
1                 NaN  
2                 NaN  
3                 NaN  
4                 NaN  
...               ...  
11716592    -0.003718  
11716593     0.009740  
11716594     0.035156  
11716595     0.000000  
11716596     0.011059  

[11716597 rows x 11 columns]

In [1]:
import pandas as pd

df = pd.read_csv('/home/hbliu/tcn_filted_data.csv')

In [2]:
df

datetime instrument       high        low       open      close  \
0         2008-07-16   SH600000  59.023102  55.958401  58.284302  56.943401   
1         2008-07-16   SH600001  11.635200  11.092900  11.635200  11.216100   
2         2008-07-16   SH600004  13.299200  12.778400  13.210300  12.867300   
3         2008-07-16   SH600005  45.175900  42.838402  45.041000  43.198002   
4         2008-07-16   SH600006  12.968700  12.226700  12.871900  12.484800   
...              ...        ...        ...        ...        ...        ...   
10478960  2023-12-18   SZ301408  16.370001  15.910000  16.209999  15.960000   
10478961  2023-12-18   SZ301419  38.160099  37.572399  37.724400  37.825699   
10478962  2023-12-18   SZ301428  42.790001  40.830002  41.490002  40.869999   
10478963  2023-12-18   SZ301429  20.578899  20.103800  20.427299  20.194799   
10478964  2023-12-18   SZ301439  14.738100  14.486100  14.637300  14.486100   

                volume  total_turnover       vwap  turnover  is_st  \
0         1.040819e+07    5.956980e+08  57.233581  0.005682  False   
1         8.598062e+06    9.706818e+07  11.289541  0.008125  False   
2         1.490872e+06    1.939623e+07  13.009984  0.003811  False   
3         1.059377e+07    4.642958e+08  43.827234  0.015189  False   
4         2.221628e+06    2.783845e+07  12.530652  0.008981  False   
...                ...             ...        ...       ...    ...   
10478960  2.164479e+06    3.487160e+07  16.110853  0.036070  False   
10478961  7.867815e+05    2.979166e+07  37.865227  0.031889  False   
10478962  2.826528e+06    1.175204e+08  41.577667  0.114589  False   
10478963  6.073243e+05    1.235602e+07  20.345014  0.020766  False   
10478964  1.403700e+06    2.044768e+07  14.566989  0.014546  False   

          is_suspended  cum_trading_day_num  
0                False                  132  
1                False                  132  
2                False                  132  
3                False                  132  
4                False                  132  
...                ...                  ...  
10478960         False                  197  
10478961         False                  211  
10478962         False                  144  
10478963         False                  165  
10478964         False                  185  

[10478965 rows x 13 columns]

In [12]:
df_st = df.loc[df['is_st']==True]
print(df_st)

          Unnamed: 0        date instrument  is_st  is_suspended
11553          11553  2008-01-02   SZ000004   True         False
11554          11554  2008-01-03   SZ000004   True         False
11555          11555  2008-01-04   SZ000004   True         False
11556          11556  2008-01-07   SZ000004   True         False
11557          11557  2008-01-08   SZ000004   True         False
...              ...         ...        ...    ...           ...
20412258    20412258  2020-04-21   SH601798   True         False
20412259    20412259  2020-04-22   SH601798   True         False
20412260    20412260  2020-04-23   SH601798   True         False
20412261    20412261  2020-04-24   SH601798   True         False
20412262    20412262  2020-04-27   SH601798   True          True

[479555 rows x 5 columns]


In [10]:
import torch
x = torch.randn((5000, 1))
y = torch.randn((5000, 1))
z = torch.concat((x, y), dim=1).transpose(1, 0)
print(z.shape)
c = torch.corrcoef(z)
print(c)

def correlation_coefficient_loss(output, target):
    x = output - output.mean()
    print(x.shape)
    y = target - target.mean()
    print(y.shape)
    z = x*y
    print(z.shape)
    r_num = torch.sum(x * y)
    print(r_num)
    r_den = torch.sqrt(torch.sum(x ** 2)) * torch.sqrt(torch.sum(y ** 2))
    r = r_num / r_den
    return r
c1 = correlation_coefficient_loss(y, x)
print(c1)



torch.Size([2, 5000])
tensor([[ 1.0000, -0.0130],
        [-0.0130,  1.0000]])
torch.Size([5000, 1])
torch.Size([5000, 1])
torch.Size([5000, 1])
tensor(-63.1694)
tensor(-0.0130)


In [1]:
import torch
x = torch.tensor([2, 1, 3, 0])
z = x.sort()
print(z)
a = torch.argsort(x)
print(a)
c = torch.argsort(a)
print(c)
print(a.sort())
b = 0.034534234
print(f'world{b:.3f}')

/home/share/anaconda3/envs/qlib-dev/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


torch.return_types.sort(
values=tensor([0, 1, 2, 3]),
indices=tensor([3, 1, 0, 2]))
tensor([3, 1, 0, 2])
tensor([2, 1, 3, 0])
torch.return_types.sort(
values=tensor([0, 1, 2, 3]),
indices=tensor([2, 1, 3, 0]))
world0.035


In [5]:
import time
now = time.strftime("%m%d_%H%M",time.localtime(time.time())) 
print(now)

1129_1559


In [2]:
a = [1, 2, 3]
b = a[1:3]
print(b)

[2, 3]


In [ ]:
class TCN_data(Dataset):
    def __init__(self, dict_data, timepoints, mode="train", T=63, H=3):
        super(TCN_data, self).__init__()
        self.fields = ['open', 'high', 'low', 'close', 'vwap', 'volume', 'total_turnover']
        # test_data = pd.read_csv(filename)
        # test_data = test_data.fillna(0.)
        self.data1 = dict_data
        # self.data1 = {f:test_data.pivot_table(index='datetime', columns='instrument', values=f) for f in self.fields} # 每一天 每一支股票的属性


        self.time_points = timepoints
        self.time_points.sort()

        train_set_point = len(self.time_points[self.time_points<'2020-01-01'])
        valid_set_point = len(self.time_points[(self.time_points>='2020-01-01') & 
                                        (self.time_points<'2021-01-01')])

        test_set_point = len(self.time_points[self.time_points>='2021-01-01'])
        assert train_set_point + valid_set_point + test_set_point == len(self.time_points)
        if mode == 'train':
            self.data_range = list(range(T, train_set_point))
        elif mode == 'valid':
            self.data_range = list(range(train_set_point, train_set_point + valid_set_point))
        else:
            self.data_range = list(range(train_set_point + valid_set_point, len(self.time_points) - H))
        # split_point = len(self.time_points[self.time_points<'2020-01-01'])
    def __len__(self):
        return len(self.data_range)
    def get_batch(self, t, T=63, H=5):
        assert t>=T and t<=len(self.time_points)-H
        tmp = []
        fds = []
        columns = self.data1['close'].columns
        valid_columes = []

        valid_columes_idx = [self.data1['close'][i].loc[self.time_points[t-T]: self.time_points[t+H+1]].isnull().any() for i in columns]
        for i in range(len(columns)):
            if not valid_columes_idx[i]:
                valid_columes.append(columns[i])
        closing_price_at_start = self.data1['close'][valid_columes].loc[self.time_points[t-T]]
        for i, f in enumerate(self.fields):
            current_data = self.data1[f][valid_columes]
            # closing_price_at_start = self.data1['close'].loc[self.time_points[t-T]]
            if f in ['open', 'high', 'low', 'close', 'vwap']:
                _field = current_data.loc[self.time_points[t-T+1]: self.time_points[t]] / closing_price_at_start

            else:
                min_num = current_data.loc[self.time_points[t-T+1]: self.time_points[t]].min()
                max_num = current_data.loc[self.time_points[t-T+1]: self.time_points[t]].max()
                _field = (current_data.loc[self.time_points[t-T+1]: self.time_points[t]] - min_num) / (max_num - min_num)

            _field = _field.fillna(0.)
            tmp.append(_field.values)

        prediction = (self.data1['open'][valid_columes].loc[self.time_points[t+H]] - self.data1['open'][valid_columes].loc[self.time_points[t+1]]) / self.data1['open'][valid_columes].loc[self.time_points[t+1]]
        percentile_ranks = prediction.rank(pct=True)
        # prediction = prediction.fillna(0.)
        Y = percentile_ranks.values
        # Y = prediction.values

        X = np.transpose(np.stack(tmp), [2, 0, 1])

        return X, Y

    def __getitem__(self, index) -> Any:
        return self.get_batch(self.data_range[index])

In [3]:
year = 2020
a = str(year) + '-01-01'
print(a)
print(type(a))
print(type('-01-01'))

2020-01-01
<class 'str'>
<class 'str'>
